title: Learning Blog
description: "My personal learning notes"
baseurl: "/blog"
theme: jekyll-theme-cayman
# links:
#   section_1:
#     - title: home
#       url: /
#       key_trigger: 1
#     - title: Test
#       url: /test
#       key_trigger: 2
